use_frameworks!

platform :ios, '8.0'

target 'ZGPageMenu_Example' do
  pod 'ZGPageMenu', :path => '../'

  target 'ZGPageMenu_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
